'use strict';
/* The financial publication correctness suite. `npm test`
 *
 * Runs every check that can be made without a password or a network, in
 * dependency order: syntax first (a broken file makes every later result
 * meaningless), then the engine, then the data it is fed, then the
 * contradictions between the two.
 *
 * An invariant failure is a FAILURE, not a warning. A financial plan that
 * disagrees with itself is worse than no plan, because it still looks
 * authoritative.
 *
 * Not run here, because they need something this process does not have:
 *   node test/test-local.js    needs TEST_PASSWORD and a running server
 *   node verify-live.js   needs the deployed site
 *
 * `test-production-live-overlay.js` starts a local server.js with synthetic
 * SITE_PASSWORD / SESSION_SECRET. Those are not production secrets.
 */

const { execFileSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');

const suites = [
  ['static sanity', 'test-static.js'],
  ['incumbent privacy guard (B77)', 'test-privacy-guard.js'],
  ['source line-ending independence', 'test-line-endings.js'],
  ['forecast engine + opening-gap regression', 'test-forecast.js'],
  ['walk-derived additionalCashRequired (chequing-only zero floor)', 'test-additional-cash-required.js'],
  ['opening-gap recovery does not auto-borrow', 'test-opening-gap-no-auto-borrow.js'],
  ['quarterly recurrence (every 3 months)', 'test-quarterly-recurrence.js'],
  ['owner-confirmed subscription bills', 'test-owner-subscription-bills.js'],
  ['Amazon Prime membership subscription', 'test-amazon-prime-membership.js'],
  ['income dependency deadline', 'test-income-deadline.js'],
  ['next due obligation', 'test-next-due.js'],
  ['next payment out', 'test-next-payment-out.js'],
  ['household schedule authority', 'test-schedule-authority.js'],
  ['question status authority', 'test-question-status.js'],
  ['unallocated / free cash', 'test-unallocated-cash.js'],
  ['compact snapshot', 'test-compact-snapshot.js'],
  ['publication totals', 'test-publication-totals.js'],
  ['homepage mission', 'test-mission.js'],
  ['plan status band + funding verdicts', 'test-status-band.js'],
  ['what the next move achieves', 'test-nextmove.js'],
  ['gap counterfactuals', 'test-counterfactuals.js'],
  ['May 2027 renewal', 'test-renewal.js'],
  ['payoff modeller', 'test-payoff.js'],
  ['household budget reconciliation', 'test-budget.js'],
  ['workbook evidence cannot overwrite owner policy', 'test-workbook-authority.js'],
  ['Groceries $900 per Seaspan pay period', 'test-groceries-payday-monthly.js'],
  ['Other spend $800/month owner target', 'test-other-spend-owner-target.js'],
  ['Other spend is not a Household Budget calendar hold', 'test-other-spend-calendar-hold.js'],
  ['spending classification reconciliation', 'test-classification.js'],
  ['Lunch Money historical actuals authority (AF-OPERATE-01)', 'test-periods-lunchmoney.js'],
  ['read-only recurring card-charge audit', 'test-recurring-audit.js'],
  ['decision-first payday operating surface (AF-OPERATE-02)', 'test-operating-surface.js'],
  ['plain-language household homepage', 'test-household-view.js'],
  ['approved Budget UI presentation', 'test-budget-ui-polish.js'],
  ['Budget owner-voice presentation', 'test-budget-owner-voice.js'],
  ['Plan homepage decision desk', 'test-plan-decision-desk.js'],
  ['cash-waterfall household homepage', 'test-cash-waterfall-view.js'],
  ['chequing availability headline', 'test-chequing-availability.js'],
  ['Current Balance is planning-hub cash only', 'test-current-balance-chequing-cash.js'],
  ['ordered payday action sheet (AF-OPERATE-03)', 'test-operate-payday-action-sheet.js'],
  ['between-paydays operating view (AF-OPERATE-04)', 'test-operate-between-paydays.js'],
  ['future financial gravity (AF-OPERATE-05)', 'test-operate-future-gravity.js'],
  ['required and extra debt answer (AF-OPERATE-06)', 'test-operate-debt-answer.js'],
  ['payday operating-surface acceptance (AF-OPERATE-07)', 'test-operate-payday-acceptance.js'],
  ['payday operating sheet six glance answers', 'test-payday-operating-sheet.js'],
  ['Plan default view layout', 'test-plan-default-view.js'],
  ['This payday printout layout order', 'test-this-payday-layout-order.js'],
  ['household nav and Plan waterfall boundary', 'test-household-nav-plan-boundary.js'],
  ['household nav mobile presentation', 'test-household-nav-presentation.js'],
  ['Talk to Atlas household surface', 'test-talk-page.js'],
  ['Talk context packet seam', 'test-talk-context.js'],
  ['Talk Gemini explainer turn', 'test-talk-ask.js'],
  ['Talk structured answer cards', 'test-talk-cards.js'],
  ['Talk citations / provenance (Queue PR 2)', 'test-talk-citations.js'],
  ['Talk household decision summary', 'test-talk-decision-summary.js'],
  ['Talk multi-turn session context (Queue PR 3)', 'test-talk-session.js'],
  ['Talk safe streaming (Queue PR 4)', 'test-talk-stream.js'],
  ['Talk deterministic Why? explanation', 'test-talk-why.js'],
  ['Talk verified follow-up references', 'test-talk-followup-refs.js'],
  ['Talk payday leftover from Forecast.runningLeftover', 'test-talk-payday-leftover.js'],
  ['Talk payday operating picture from Forecast.paydayAllocation', 'test-talk-payday-picture.js'],
  ['Talk payday remaining bills from Forecast.obligations.items', 'test-talk-payday-remaining-bills.js'],
  ['Talk Which one? after earned A-vs-B (B103 Slice 4)', 'test-talk-which-one-preference.js'],
  ['Talk hypothetical extra adapter (Talk Slice 6B)', 'test-talk-hypothetical.js'],
  ['owner decision posture policy (Talk Slice 5)', 'test-decision-posture.js'],
  ['hypothetical extra-payment scenario (Talk Slice 6)', 'test-hypothetical-extra-payment.js'],
  ['hypothetical extra-payment comparison (Decision Intelligence foundation)', 'test-hypothetical-extra-payment-comparison.js'],
  ['Forecast baseline trajectory (Financial Trajectory)', 'test-baseline-trajectory.js'],
  ['Forecast baseline trajectory three-stage funding decomposition', 'test-baseline-trajectory-funding-stages.js'],
  ['Forecast stage1 income named Dale/Amanda lines', 'test-baseline-trajectory-income-lines.js'],
  ['Forecast stage1 bills / obligations / householdBudget named lines', 'test-baseline-trajectory-stage1-component-lines.js'],
  ['Forecast stage2 commitment named lines', 'test-baseline-trajectory-stage2-commitment-lines.js'],
  ['Forecast baseline trajectory pay-period series (B105l)', 'test-baseline-trajectory-pay-period-series.js'],
  ['Forecast provisional recent pay-period normal spending', 'test-provisional-normal-spending-baseline.js'],
  ['Road Ahead standalone period surplus/deficit', 'test-standalone-road-ahead-surplus.js'],
  ['Road Ahead independent Month / Pay Period financial reconciliation', 'test-road-ahead-reconciliation.js'],
  ['Forecast residual pay-period identity vs Budget This Pay Period', 'test-pay-period-residual-identity.js'],
  ['Forecast baseline trajectory additional-debt-payment scenario (O4)', 'test-baseline-trajectory-scenario.js'],
  ['Dale/Seaspan estimated payroll regime (independent stubs)', 'test-dale-payroll-regime.js'],
  ['Credit page — what do we owe (Forecast.creditAccounts)', 'test-credit-page.js'],
  ['Planning page — Forecast.majorPlans rendered', 'test-planning-page.js'],
  ['Plan spend page — Forecast.majorPlans reprinted', 'test-plan-spend-page.js'],
  ['Planning Road Ahead phone-native presentation', 'test-planning-road-mobile-presentation.js'],
  ['Bills page — Forecast.householdBills rendered', 'test-bills-page.js'],
  ['Subscriptions page — Forecast.householdSubscriptions rendered', 'test-subscriptions-page.js'],
  ['Plan calendar bill sections', 'test-plan-bill-calendar-periods.js'],
  ['Plan calendar waterfalls', 'test-plan-calendar-waterfalls.js'],
  ['Dog food every-other-Seaspan payday cadence', 'test-dog-food-monthly-cadence.js'],
  ['Household planned target removed', 'test-household-target-removed.js'],
  ['Household Budget Other spending residual', 'test-household-budget-other-spending.js'],
  ['Uncategorised debit enters Other Spending once', 'test-uncategorised-other-spending.js'],
  ['Household Budget Spent transaction drill-down', 'test-household-budget-spent-drilldown.js'],
  ['Household Budget overlay Spent drill-down when recon withheld', 'test-household-budget-overlay-spent-drilldown.js'],
  ['header freshness source identity (history vs live overlay spending)', 'test-header-freshness-source-identity.js'],
  ['Household Budget Spent possible-replacement drill-down', 'test-household-budget-spent-possible-replacement-drilldown.js'],
  ['current-period Household Budget classification', 'test-current-period-household-budget-classification.js'],
  ['cancelled-service unexpected charge', 'test-cancelled-service-unexpected-charge.js'],
  ['Lunch Money Dale/Amanda guilt-free category assignment', 'test-lunchmoney-dale-amanda-guilt-free.js'],
  ['BC Hydro Sep 4 Other-spending classification', 'test-bc-hydro-sep4-classification.js'],
  ['Bell Mobility Travel Visa Other-spending classification', 'test-bell-travelvisa-classification.js'],
  ['Bell Sep 15 2026 same-account BILLS split settlement', 'test-bell-same-account-split.js'],
  ['Bell standing BILLS two-leg settlement', 'test-bell-standing-bills-split.js'],
  ['BC Hydro equal monthly payment $199 timing repair and account credit', 'test-hydro-equal-payment.js'],
  ['standing Fortis / Shaw / Netflix / TD / YouTube / Spotify / ChatGPT Plus Dale / ChatGPT Plus Amanda / iCloud settlement identities', 'test-bill-settlement-identities.js'],
  ['calendar / Budget bills reprint representedActuals as Paid', 'test-calendar-represented-actuals-paid.js'],
  ['unresolved pending→posted household-spend treatment', 'test-unresolved-pending-posted-spend.js'],
  ['current-period Other-residual classification contract', 'test-current-period-other-residual-contract.js'],
  ['salary recognition and payroll drift', 'test-salary-recognition-drift.js'],
  ['owner income-recognition policy 2026-09-11', 'test-income-recognition-owner-policy.js'],
  ['Canada Child Benefit amount $219.45', 'test-child-benefit-amount.js'],
  ['Canada Child Benefit privacy-stripped overlay match', 'test-child-benefit-overlay-match.js'],
  ['Other Income payday waterfall', 'test-other-income.js'],
  ['proven household-internal cash movement', 'test-household-internal-movement.js'],
  ['leftover vs Current Balance operating-cash explanation', 'test-leftover-operating-cash-explanation.js'],
  ['leftover vs BILLS ACCOUNT cash explanation', 'test-leftover-bills-cash-explanation.js'],
  ['payday-boundary chequing-a posted cash observation', 'test-payday-boundary-bills-observation.js'],
  ['payday-boundary chequing-a observation persist', 'test-payday-boundary-observation-persist.js'],
  ['posted chequing-a movement evidence set', 'test-chequing-a-posted-movements.js'],
  ['operating-cash explanation after Q07 after budget polish', 'test-operating-cash-explanation-placement.js'],
  ['Plan payday operating periods', 'test-payday-operating-periods.js'],
  ['Sep 10 to Sep 11 payday rollover boundary', 'test-payday-rollover-boundary.js'],
  ['Plan payday waterfall balance date and post-payday identity', 'test-plan-payday-waterfall-balance.js'],
  ['owner-policy Payday balance waterfall', 'test-payday-balance-owner-policy.js'],
  ['payday snapshot vs live Current Balance', 'test-payday-snapshot-live-balance.js'],
  ['payday opening authority from dated opening', 'test-payday-opening-authority.js'],
  ['payday waterfall bill load vs remaining-only leftover', 'test-payday-waterfall-bill-load.js'],
  ['payday settlement survives live opening advancement', 'test-payday-settlement-boundary.js'],
  ['payday Household Budget max(planned, actual) contract', 'test-household-budget-waterfall-contract.js'],
  ['current-pay-period Balance After Deductions (owner 2026-09-21)', 'test-predicted-ending-balance.js'],
  ['hub-account Current Balance and Balance After Deductions', 'test-hub-account-balance-after-deductions.js'],

  ['Plan unavailable operating state', 'test-plan-unavailable-surface.js'],
  ['Plan next-period lookahead and week picker', 'test-plan-lookahead-week.js'],
  ['Plan completed historical pay periods', 'test-historical-pay-periods.js'],
  ['Plan payday carryover trend', 'test-payday-carryover-trend.js'],
  ['Plan actual vs budget digest', 'test-plan-budget-digest.js'],
  ['weekly cap conversion + discretionary room', 'test-weekly-cap.js'],
  ['food and fuel monthly figures', 'test-food-fuel.js'],
  ['phase titles and risk list', 'test-plan-phases.js'],
  ['Deep Dive derived totals', 'test-deepdive.js'],
  ['HELOC Deep Dive current-opening agreement (B19)', 'test-heloc-deepdive.js'],
  ['coupled cash and debt', 'test-debt.js'],
  ['debt absorption covers the cash horizon', 'test-debt-absorption-horizon.js'],
  ['amortising payoff stops later interest share', 'test-amortizing-payoff-horizon.js'],
  ['live recurring debt and cash horizon reconciliation', 'test-live-debt-horizon.js'],
  ['HELOC crossing-date authority', 'test-heloc-crossing-authority.js'],
  ['HELOC Forecast Required-debt cash minimum', 'test-heloc-forecast-cash-minimum.js'],
  ['authority invariants', 'test-invariants.js'],
  ['authority surface coverage', 'test-authority-coverage.js'],
  ['evidence-use register routing', 'test-evidence-use-register.js'],
  ['knowledge-evidence register (external-reference)', 'test-knowledge-evidence-register.js'],
  ['live household reconciliation', 'test-live-household.js'],
  ['duplicate live-fact cleanup (B93)', 'test-dedup-facts.js'],
  ['current-balance conclusions are Forecast-derived', 'test-derive-current-headroom.js'],
  ['refresh isolation (B92)', 'test-refresh-isolation.js'],
  ['non-writing reconciliation (B91)', 'test-reconcile.js'],
  ['current-state cutover (B91)', 'test-cutover.js'],
  ['unresolved once obligations survive cutover', 'test-cutover-unresolved.js'],
  ['commitment settlement (B91 D3)', 'test-settlement.js'],
  ['settled commitment not carried through priorAsOf', 'test-settled-commitment-priorasof.js'],
  ['Hydro dated obligation (B91 D4+D5)', 'test-hydro.js'],
  ['Amanda income split (B91 D2)', 'test-amanda-income.js'],
  ['card current state (B91 D8)', 'test-card-state.js'],
  ['schedule vs posted (B91 D7)', 'test-posting.js'],
  ['near-boundary payday output (B91 D11)', 'test-near-boundary.js'],
  ['B91 live current-state cutover', 'test-b91-cutover.js'],
  ['merge-card check behaviour', 'test-mergecard.js'],
  ['figures comment Plan/Credit/Planning scope (B82/B100)', 'test-figures-comment.js'],
  ['figures snapshot Credit and Planning coverage (B100)', 'test-figures-snapshot-credit-planning.js'],
  ['Codex Cursor repair gate', 'test-codex-cursor-repair.js'],
  ['Atlas review-block card sync', 'test-atlas-review-block.js'],
  ['Atlas bounded re-review handoff', 'test-atlas-api-rereview.js'],
  ['Atlas manual REQUIRED review handoff', 'test-atlas-first-review.js'],
  ['Merge Card primary-risk projection', 'test-atlas-primary-risk.js'],
  ['GitHub PR-head confirmation after push', 'test-github-pr-head-sync.js'],
  ['local main sync safety contract', 'test-sync-main.js'],
  ['failed-check auto-repair contract', 'test-atlas-test-repair.js'],
  ['read-only provider observation (connectivity spike)', 'test-provider-observe.js'],
  ['local Lunch Money credential resolver', 'test-local-credentials.js'],
  ['live pending observations (B91 / B78)', 'test-pending-observe.js'],
  ['idempotent Lunch Money identity (B78 / AF-INGEST-01)', 'test-b78-identity.js'],
  ['trusted canonical refresh (B81 / AF-LIVE-02)', 'test-b81-refresh.js'],
  ['opening-cutover preflight (B81 read-only)', 'test-cutover-preflight.js'],
  ['bounded cutover pending writer (B81)', 'test-b81-pending-writer.js'],
  ['bounded opening-cutover writer (B81)', 'test-b81-opening-cutover.js'],
  ['opening state transition (B81)', 'test-b81-opening-state.js'],
  ['opening artifact recovery (B81)', 'test-b81-opening-recovery.js'],
  ['live plan overlay without rewriting openings', 'test-live-plan.js'],
  ['live overlay unresolved same-day inbound', 'test-live-unresolved-inbound.js'],
  ['production read-only live overlay boundary', 'test-production-live-overlay.js'],
  ['read-only assistant interface', 'test-assistant-interface.js'],
  ['Aug. 16 household evidence absorption', 'test-aug16-evidence.js'],
  ['2026-09-03 card-charge evidence intake', 'test-card-charge-evidence-2026-09-03.js'],
  ['telecom current-regime closeout', 'test-telecom-current-regime.js'],
  ['Bell card-paid baseline gravity', 'test-bell-card-paid.js'],
  ['Bell dated mid-month planning', 'test-bell-dated-planning.js'],
  ['Bell Sep 2026 once $283.94 and standing $160 from Oct', 'test-bell-sep15-2026.js'],
  ['Square One yearly card-paid home insurance', 'test-square-one-annual-bill.js'],
  ['HELOC Q19 + Bell Q18 evidence closeout', 'test-q19-q18-closeout.js'],
  ['Q1 planning policy (2026-08-29 coaching gravy)', 'test-q1-planning-policy.js'],
  ['major future costs on the master plan', 'test-major-future-costs.js'],
  ['commitment month-only day-15 dating', 'test-commitment-month-day15.js'],
  ['Fusion household + Warriors U13 plan commitments', 'test-fusion-warriors-plan-commitments.js'],
  ['master forecast engine (B94 / AF-PLAN-01)', 'test-master-forecast.js'],
  ['end-to-end payday proof (B96 / AF-PLAN-02)', 'test-b96-payday.js'],
  ['payday allocation waterfall', 'test-payday-allocation.js'],
  ['Prepare Ahead is paydayAllocation.protectedPath', 'test-prepare-ahead.js'],
  ['payday Household Budget cash identity', 'test-payday-household-cash-identity.js'],
  ['payday reserve itemization', 'test-payday-reserve-detail.js'],
  ['current-period actuals action plan', 'test-current-period-actuals.js'],
  ['this-payday already-paid set and cancelled CMAW drop', 'test-this-payday-already-paid.js'],
  ['automatic-payment settlement reconciliation', 'test-automatic-payment-settlement.js'],
  ['Triangle and MBNA card-minimum settlement', 'test-card-minimum-settlement.js'],
  ['TD / Cash Back / Travel Visa PAYMENT - THANK YOU card-minimum identity', 'test-payment-thank-you-card-minimum.js'],
  ['Dale-gated Noble / HELOC / TDCC represented settles', 'test-dale-gated-represented-settles.js'],
  ['final Affirm payment owner correction', 'test-affirm-final.js'],
  ['retire cancelled CMAW union-dues recurrence (AF-REFRESH-01)', 'test-refresh-01-union-dues.js'],
  ['on-demand observation receipt (AF-REFRESH-02)', 'test-refresh-02-observation-receipt.js'],
  ['obligation reconciliation receipt (AF-REFRESH-03)', 'test-refresh-03-obligation-reconciliation.js'],
  ['bounded canonical refresh preview (AF-REFRESH-04)', 'test-refresh-04-canonical-preview.js'],
  ['recompute operating answer from refreshed state (AF-REFRESH-05)', 'test-refresh-05-operating-answer.js'],
  ['refresh trust on the operating surface (AF-REFRESH-06)', 'test-refresh-06-trust-surface.js'],
  ['live closed-loop acceptance and cleanup (AF-REFRESH-07)', 'test-refresh-07-live-acceptance.js'],
  ['balance history as a refresh by-product (B20 / AF-HIST-01)', 'test-b20-history.js'],
];

let failed = [];
for (const [name, file] of suites) {
  if (!fs.existsSync(path.join(__dirname, file))) {
    console.log(`\n\x1b[31m✗\x1b[0m ${name} — ${file} is missing`);
    failed.push(name);
    continue;
  }
  console.log(`\n\x1b[1m──────── ${name} ────────\x1b[0m`);
  try {
    execFileSync(process.execPath, [path.join(__dirname, file)], { cwd: ROOT, stdio: 'inherit' });
  } catch {
    failed.push(name);
  }
}

console.log('\n' + '═'.repeat(60));
if (failed.length) {
  console.log(`\x1b[31mFAILED\x1b[0m — ${failed.length} of ${suites.length} suites: ${failed.join(', ')}`);
  process.exit(1);
}
console.log(`\x1b[32mALL ${suites.length} SUITES PASSED\x1b[0m`);
